name: flutter_flame_game
description: Pixel Adventure Clone.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.8.2
  flame_tiled: ^1.12.0
  flame_audio: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/tiles/
    - assets/images/Menu/Buttons/
    - assets/images/Background/
    - assets/images/Terrain/
    - assets/images/HUD/
    - assets/images/Items/Fruits/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Traps/Saw/
    - assets/images/Main Characters/
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/Virtual Guy/
    - assets/images/Enemies/Chicken/

  fonts:
    - family: PixelifySans
      fonts:
        - asset: fonts/PixelifySans-Regular.ttf
          weight: 400
        - asset: fonts/PixelifySans-Medium.ttf
          weight: 500
        - asset: fonts/PixelifySans-Bold.ttf
          weight: 700
        - asset: fonts/PixelifySans-SemiBold.ttf
          weight: 600
